import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "고객 페이지",
    description: "Generated by create next app",
};

export default function ItemsLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={"bg-[#ddd] contain-fluid"}>
            <div className={"row justify-content-center m-4"}>
               <h1>Grids & Circle</h1>
            </div>
            <div className={"row justify-content-center m-4 bg-white"}>
                {children}
            </div>

        </div>
    );
}
