import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
    title: "고객 페이지",
    description: "Generated by create next app",
};

export default function ItemsLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="bg-[#ddd] container-fluid row justify-content-center h-screen">
            <div className="flex justify-center ">
                <h1 className={"text-2xl m-4"}>Grids & Circle</h1>
            </div>
            <div className="flex justify-center ">
                {children}
            </div>
        </div>
    );
}
