import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

export const metadata: Metadata = {
    title: "홈화면",
    description: "Generated by create next app",
};

export default function ItemsLayout({
                                        children,
                                    }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body>
                {/* 네비게이션 바 */}
                <nav className="bg-white shadow-md fixed top-0 left-0 right-0 z-50">
                    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
                        <div className="flex justify-between items-center h-16">
                            {/* 로고/브랜드명 */}
                            <div className="flex items-center">
                                <Link href="/" className="text-2xl font-bold text-gray-800">
                                    Grids & Circle
                                </Link>
                            </div>
                            
                            {/* 네비게이션 메뉴 */}
                            <div className="flex space-x-8">
                                <Link 
                                    href="/items" 
                                    className="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                                >
                                    고객 페이지
                                </Link>
                                <Link 
                                    href="/adm" 
                                    className="text-gray-600 hover:text-gray-900 px-3 py-2 rounded-md text-sm font-medium transition-colors"
                                >
                                    관리자 페이지
                                </Link>
                            </div>
                        </div>
                    </div>
                </nav>
                
                {/* 메인 컨텐츠 - 네비게이션 바 높이만큼 패딩 추가 */}
                <main className="pt-16">
                    {children}
                </main>
            </body>
        </html>
    );
}
